### ISSUE TITLE
Outdated rocketchat

### ISSUE THREAD

**Issue by niklaskeerl** [Sierra1011/chocolateypackage-rocketchat#1]
Hey @Sierra1011 ,
thank you for maintaining rocketchat on chocolatey :)
When starting the rocket chat client the last few days, I was notified that there is a new version available.
Could you update to the latest version please? :)
If you use a rss reader, you can check for new releases using this link: https://github.com/RocketChat/Rocket.Chat.Electron/releases.atom
Alternatively, you could run your autoupdate script on a schedule (daily maybe) using GitHub actions.
Thanks for your help in advance :)

**Comment by niklaskeerl** [comment]
Thank you for updating :)

**Comment by Sierra1011** [comment]
Hi Niklas, massive apologies - I've been meaning to get this automated for a while, so I'll work on that, but it's been updated in the meantime.
Thanks!

**Comment by niklaskeerl** [comment]
My suggestion would be to run your autoupdate Powershell script on a schedule (daily) using GitHub Actions. Then you don't have to worry about it anymore :)
https://jasonet.co/posts/scheduled-actions/

If you want some help, just let me know :)

Also, no need to apologize, I am thankful that you volunteered to maintain this project :heart: .

**Comment by Sierra1011** [comment]
Thanks! It's on the list :)
