### ISSUE TITLE
Push 3.9.14 release to Chocolatey Community Repo

### ISSUE THREAD

**Issue by compuguy** [Sierra1011/chocolateypackage-rocketchat#16]
I noticed in 801c1b62b35a1411c114d4a6fb143fe51b839a1a that you updated the package to 3.9.14. If you get a chance @Sierra1011 can you push this to the https://community.chocolatey.org/ repo?

**Comment by compuguy** [comment]
Any updates on this @Sierra1011? Looks like 3.9.12 is the latest available on the repo: https://community.chocolatey.org/packages/rocketchat/#versionhistory

**Comment by Sierra1011** [comment]
Hey @compuguy apologies .14 should now be available on chocolatey.

**Comment by compuguy** [comment]
Not a problem @Sierra1011. Life happens. I honestly forgot about this. So thank you for pushing this!
