### ISSUE TITLE
allow passing custom param /disableAutoUpdates

### ISSUE THREAD

**Issue by bbrendon** [Sierra1011/chocolateypackage-rocketchat#9]
Is it possible to somehow be able to pass `/disableAutoUpdates` to choco when installing this? I would like to remove the RC popup to update and manage the updates using choco instead.

The disableAutoUpdates flag is documented on this page:  https://github.com/RocketChat/Rocket.Chat.Electron

**Comment by Sierra1011** [comment]
Hi. You'd be best off looking into passing an Install-Argument into chocolatey. https://docs.chocolatey.org/en-us/choco/commands/install#options-and-switches
